apiVersion: "tinkerbell.org/v1alpha1"
kind: Hardware
metadata:
  name: node-02
  namespace: default 
spec:
  disks:
    - device: /dev/nvme0n1
  metadata:
    facility:
      facility_code: alekslab
    manufacturer:
      slug: hardkernel
    instance:
      userdata: ""
      hostname: "node-02"
      id: "00:1e:06:45:14:78"
      operating_system:
        distro: "ubuntu"
        os_slug: "ubuntu_20_04"
        version: "20.04"
  interfaces:
    - dhcp:
        arch: x86_64
        hostname: node-02
        ip:
          address: 192.168.49.12
          gateway: 192.168.48.1
          netmask: 255.255.255.0
        lease_time: 86400
        mac: 00:1e:06:45:14:78
        name_servers:
          - 192.168.2.1
          - 8.8.8.8
        uefi: true
      netboot:
        allowPXE: true
        allowWorkflow: true
