# source: https://github.com/tinkerbell/charts/blob/main/tinkerbell/stack/values.yaml
stack:
  enabled: true
  name: tink-stack
  service:
    type: LoadBalancer
  selector:
    app: tink-stack
  loadBalancerIP: 192.168.49.0
  lbClass: kube-vip.io/kube-vip-class
  image: nginx:1.23.1
  hook:
    enabled: true
    name: hook-files
    port: 8080
    image: alpine
    downloads:
      - url: https://github.com/tinkerbell/hook/releases/download/v0.7.0/hook_x86_64.tar.gz
        sha512sum:
          kernel: "7c35042d35c003ae1f424e503ad6edf21854bc70b24b37006e810c3c8a92543420eed129c14e364769b0f32c27bdf4c61299fce8f8156af7477cac6a43931a20  vmlinuz-x86_64"
          initramfs: "be7c3d57e2d73bfa4e41a2b5740c722b1c83722e4388b3cff9017192fce43ede360221e3095c800e511d7b4bce6065f2906883421409dd6d983412418a8d903e  initramfs-x86_64"
      - url: https://github.com/tinkerbell/hook/releases/download/v0.7.0/hook_aarch64.tar.gz
        sha512sum:
          kernel: "2f1bdbf64380e281288f54c6ddd29221d8a007d29b40f405da0592ed32ef6e52695fc5071e05b2db3f075122943d62a2c266704d154a16ffb7b278c70538e7da  vmlinuz-aarch64"
          initramfs: "5adc51798c8699f5f257599aabb999e2c2f65a07c9f8607c65510e57122b3e5c53196819e7ececdcda7b8fef47ba597ea7c4b53f2f4a92e236b20e355443eefe  initramfs-aarch64"
  kubevip:
    enabled: true
    name: kube-vip
    image: ghcr.io/kube-vip/kube-vip:v0.5.7
    imagePullPolicy: IfNotPresent
    roleName: kube-vip-role
    roleBindingName: kube-vip-rolebinding

# boots chart overrides
boots:
  image: quay.io/tinkerbell/boots:v0.8.0
  env:
    - name: DATA_MODEL_VERSION
      value: "kubernetes"
    - name: FACILITY_CODE
      value: "lab1"
    - name: HTTP_BIND
      value: "192.168.49.0:80"
    - name: MIRROR_BASE_URL
      value: http://192.168.49.0:8080
    - name: BOOTS_OSIE_PATH_OVERRIDE
      value: http://192.168.49.0:8080
    - name: PUBLIC_IP
      value: 192.168.49.0
    - name: PUBLIC_SYSLOG_FQDN
      value: 192.168.49.0
    - name: SYSLOG_BIND
      value: 192.168.49.0:514
    - name: TINKERBELL_GRPC_AUTHORITY
      value: 192.168.49.0:42113
    - name: TINKERBELL_TLS
      value: "false"
    - name: BOOTS_LOG_LEVEL
      value: "debug"
    - name: BOOTS_EXTRA_KERNEL_ARGS
      value: "tink_worker_image=quay.io/tinkerbell/tink-worker:v0.8.0"
  hostNetwork: true

# hegel chart overrides
hegel:
  image: quay.io/tinkerbell/hegel:v0.10.1

# rufio chart overrides
rufio:
  image: quay.io/tinkerbell/rufio:v0.1.0

# tink chart overrides
tink:
  controller:
    image: quay.io/tinkerbell/tink-controller:v0.8.0
  server:
    image: quay.io/tinkerbell/tink:v0.8.0
